### ISSUE TITLE
not able to set a specific location 

### ISSUE THREAD

**Issue by rocks1997** [mrsudarshanrai/Weather-app-extension#1]
I am trying out your extension. but it bounces around for multiple locations. I can search for a location but am not able to set a default location for it which will open every time I open the extension.

**Comment by mrsudarshanrai** [comment]
Hi @rocks1997 ,
I have not implemented this feature yet, but I will try to implement it by tomorrow.
I was thinking of adding this feature, but forgot in time. Thanks for pointing out.

**Comment by rocks1997** [comment]
That will be great

**Comment by mrsudarshanrai** [comment]
@rocks1997 update has been published with discussed feature. I am closing this issue now. If you find any issue or want other feature please issues are welcome ☺️
